name: Visualization and Graphics Lab
author: University of San Francisco

encoding: utf-8
timezone: America/Los_Angeles

paginate: 5
paginate_path: "/blog/page:num/"
permalink: "blog/posts/:year_:month_:day_:slug.html"

sass:
  style: compressed
