name: Visualization and Graphics Lab
author: University of San Francisco

# Filter
show_drafts: null
future: true
unpublished: false
encoding: utf-8

# Output
permalink: date
timezone: America/Los_Angeles
